### ISSUE TITLE
[FEAT]: 경매글 작성 및 조회 기능 개발

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#1]
## 📌 이슈 내용
> 경매글 작성 api 구현
> 경매글 단건 조회 및 리스트 조회 api 구현

<br>

## 📝 To-do
- [x] 경매글 작성 요청 시 유효성 검증
- [x] 경매글 리스트 조회 시 정렬 방법에 따라 정렬
- [x] 무한 스크롤 가능하도록 필요한 정보 반환

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
