### ISSUE TITLE
[FIX]: 중복 및 변경된 코드를 하나의 코드로 일치시키기

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#10]
## 🤷‍♀ 문제 상황
> Member 패키지 등 각자 구현해서 사용하던 코드가 중복되거나 변경사항으로 일치하지 않아 하나로 맞추기로 함

<br>

## ✨ 해결 방법
> 회의를 통해 관련코드들을 수정하기로 함

<br>

## 📝 To-do
- [x] point 및 test point 패키지의 코드들 import문 변경
- [x] PointRepository 쿼리문 수정
- [x] PointType에 GET 추가
- [x] PointBalanceServiceDto, PointHistoryServiceDto의 포인트 수량관련 값들 자료형 long으로 수정
- [x] PointHistory의 포인트 자료형 long으로 수정
- [x] member 패키지내 Member, MemberErrorCode, MemberException, MemberRepository 삭제 
- [x] 시큐리티 설정 추가
- [x] 시큐리티 설정파일 config 패키지로 이동
- [x] 테스트코드 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
