### ISSUE TITLE
[FIX]: 도커이미지가 설정되지 않는 이슈3

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#100]
## 🤷‍♀ 문제 상황
> 경로를 찾지 못하는 문제
> 잘못된 명령어를 사용

<br>

## ✨ 해결 방법
> 경로와 명령어를 수정

<br>

## 📝 To-do
- [x] 해당 이슈의 완료 조건입니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
