### ISSUE TITLE
[FIX]: auctionService의 instantPurchaseAuction 메서드에서 memberId를 buyer.getEmail()로 변경

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#106]
## 🤷‍♀ 문제 상황
>chat_with_jwt merge 후 값이 변경이 되지 않은 부분이 발생

<br>

## ✨ 해결 방법
>memberId -> buyer.getEmail()로 변경

<br>

## 📝 To-do
- [x] 즉시 구매 기능이 실행되어야 합니다.

<br>

## 🤝 관련 이슈
- #104 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
