### ISSUE TITLE
[FEAT]: ec2에 https 적용하기 

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#108]
## 📌 이슈 내용
> 보안을 위해 https를 적용해야 합니다.
> 프론트엔드와의 통신을 위해 https를 적용해야 합니다.

<br>

## 📝 To-do
- [x] ec2에 https를 적용합니다.
- [x] 도메인명을 변경합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
