### ISSUE TITLE
[FIX]: 토큰기능 추가로 인한 코드 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#109]
## 🤷‍♀ 문제 상황
> 포인트, 주문, 알림, 결제 기능을 토큰을 사용하는 로직으로 수정해야합니다.

<br>

## ✨ 해결 방법
> 기존 하드코딩된 회원id 값을 토큰을 사용하는 로직으로 수정해야합니다.

<br>

## 📝 To-do
- [x] 포인트 기능 수정
- [x] 주문 기능 수정
- [x] 알림 기능 수정
- [x] 결제 기능 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
