### ISSUE TITLE
[FIX]: 소셜로그인 첫 가입시 임의 아이디 소셜 제공자_UUID로 변경

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#110]
## 🤷‍♀ 문제 상황
> 소셜 제공자의 ID는 체계가 변경될 가능성이 있고 사용자의 식별을 유지하는 데 어려움이 생길 수 있습니다.
<br>

## ✨ 해결 방법
> 소셜 제공자_UUID 랜덤 값으로 변경
ex) google_234573813523

<br>

## 📝 To-do
- [x] 소셜 제공자의 고유 식별자 사용하지 않고 UUID 랜덤 값 사용

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
