### ISSUE TITLE
[FIX]: 소셜 로그인 중복 이메일로 인한 계정 통합 예외 처리 구현

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#112]
## 🤷‍♀ 문제 상황
> 구글로 회원가입이 되었는데 구글에서 사용한 이메일로 카카오로 로그인하면
구글로 가입한 계정이 로그인되어 중복된 이메일에 관한 예외처리가 필요한 상황

<br>

## ✨ 해결 방법
> 어떻게 해결했는지 적어주세요.

<br>

## 📝 To-do
- [x] 이메일이 중북되었을 때 어느 것으로 회원가입 하였는지, 메시지와 함께 예외처리
- [x] 커스텀 예외처리 구현

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
