### ISSUE TITLE
[FEAT]: 경매 리스트 조회 param에 자식 카테고리도 추가

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#113]
## 📌 이슈 내용
> 경매 리스트 조회 api 의 param값에 자식 카테고리도 작성하도록 변경합니다.

<br>

## 📝 To-do
- [x] 경매 리스트 조회 api param값에 자식 카테고리를 작성할 수 있도록 추가

<br>

## 🤝 관련 이슈
- #1 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
