### ISSUE TITLE
[FIX]: build.yml oauth2 redirect-uri 변경

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#116]
## 🤷‍♀ 문제 상황
> redirect-uri가 로컬 도메인으로 설정되어 배포된 서버에 소셜로그인이 작동하지 않은 상황 발생

<br>

## ✨ 해결 방법
> https://dddang.store/ 배포 도메인으로 변경했습니다.

<br>

## 📝 To-do
- [ ] redirect-uri 변경
- [ ] 구글, 네이버, 카카오 Callback URL 추가

<br>

## 🤝 관련 이슈
- #22

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
