### ISSUE TITLE
[FIX]: 카테고리 조회 추가

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#118]
## 🤷‍♀ 문제 상황
> 카테고리 전체 조회 추가
ex) 모든 부모 카테고리, 모든 자식 카테고리들 조회

<br>

## ✨ 해결 방법
> 

<br>

## 📝 To-do
- [x] 전체 카테고리 조회
- [x] 캐싱 사용

<br>

## 🤝 관련 이슈
- #60 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [ ] issue 제목은 유의미한가?
- [ ] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
