### ISSUE TITLE
[FEAT]: 로드밸런서 헬스체크용 api 만들기

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#126]
## 📌 이슈 내용
> 현재 헬스체크의 경로가 모든 경매를 조회하는 경로로 설정되어 있어 추후 서버 부하 증가 등의 문제가 발생할 여지가 있습니다.
> 헬스체크용 경로를 따로 만들어 이 문제를 해결하려고 합니다.

<br>

## 📝 To-do
- [x] 헬스체크용 api 추가

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
