### ISSUE TITLE
[FIX]: 채팅방 목록 조회시 잘못된 값을 받아 회원 조회를 하지 못하는 문제 발생

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#133]
## 🤷‍♀ 문제 상황
> 채팅방 목록 조회 API에서 findChatRoomsByMemberId 인자 값에 
회원 아이디가 들어가야 하는데 이메일이 들어가서회원 조회가 되지 않는 상황

<br>

## ✨ 해결 방법
> 인자 값을 회원 아이디로 변경하였습니다.
<br>

## 📝 To-do
- [x] 인자 값 getUsername() -> .getName() 변경
- [x] 채팅방 서비스 예외처리 변경
- [x] Response Dto에 생성날짜 값 수정

<br>

## 🤝 관련 이슈
- #95 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
