### ISSUE TITLE
[FEAT]: 채팅 부가기능 추가

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#135]
## 📌 이슈 내용
> 채팅 메시지 조회 기능 구현

<br>

## 📝 To-do
- [x] 채팅 메시지 조회 기능
- [x] 채팅방 response 반환값 간소화
- [x] api 권한 검증 추가

<br>

## 🤝 관련 이슈
- #95 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
