### ISSUE TITLE
[FEAT]: 채팅 부가기능 추가 2

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#137]
## 📌 이슈 내용
> 채팅 부가기능 추가

<br>

## 📝 To-do
- [x] 경매방 이름으로 채팅방 검색 기능 구현
- [x] 채팅방 목록에서 마지막 채팅, 날짜 출력
- [x] 읽지 않은 메시지 기능 구현

<br>

## 🤝 관련 이슈
- #135

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
