### ISSUE TITLE
[FEAT]: 포인트 내역 조회시 응답에 날짜 포함시키기

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#139]
## 📌 이슈 내용
> 포인트 내역 조회시 응답으로 생성날짜가 포함되어 있지 않아 추가해야합니다

<br>

## 📝 To-do
- [x] 포인트 내역조회 응답에 생성날짜 추가

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
