### ISSUE TITLE
[FEAT]: 경매 종료 시키기

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#14]
## 📌 이슈 내용
> 경매 생성 시 판매자가 작성한 경매 종료 날짜에 맞춰 경매 종료

<br>

## 📝 To-do
- [x] 경매 종료 날짜에 맞춰 경매가 종료됩니다.
- [x] 경매 종료 후 낙찰자가 선정됩니다.
- [x] 낙찰자가 없어도 경매는 종료됩니다.
- [x] 즉시 구매가 진행된 경우 경매의 남은 기간에 상관없이 종료됩니다.
- [x] 낙찰자가 있는 경우 판매자와의 채팅방이 생성됩니다.
- [x] 낙찰자가 있는 경우 경매 종료와 함께 구매자의 보유 포인트가 감소합니다.
- [x] 경매가 종료되었음을 판매자에게 알림을 보내고 낙찰자가 있는 경우 낙찰자에게 알림을 보냅니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
