### ISSUE TITLE
[FEAT]: 경매종료, 즉시구매시 포인트내역 저장

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#141]
## 📌 이슈 내용
> 포인트 내역 정보 저장이 안되고 있음
> 경매종료시 낙찰자의 포인트 감소 내역이 저장되어야 합니다.
> 즉시구매시 낙찰자의 포인트 감소 내역이 저장되어야 합니다.

<br>

## 📝 To-do
- [x] 경매종료시 낙찰자의 포인트 감소 내역 저장하기
- [x] 즉시구매시 낙찰자의 포인트 감소 내역 저장하기

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
