### ISSUE TITLE
[FIX]: 받지 못한 알림 처리 로직 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#147]
## 🤷‍♀ 문제 상황
> EventSource API는 HTTP 요청에 헤더를 추가하는 기능을 제공하지 않는다고 해서 lastEventId값을 받지못함

<br>

## ✨ 해결 방법
> EventSource API는 HTTP 요청에 헤더를 추가하는 기능을 제공하지 않는다고 해서 파라미터로 값을 받도록 수정

<br>

## 📝 To-do
- [x]  파라미터로 값을 받도록 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
