### ISSUE TITLE
[FEAT]: 경매 구매 확정시 자동으로 채팅방 나가기 기능 구현

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#150]
## 📌 이슈 내용
> 구매 확정이 되면 채팅방이 자동으로 삭제됩니다.
<br>

## 📝 To-do
- [x] 구매 확정시 레디스에 저장된 채팅방 삭제
- [x] 자동 구매 확정시 레디스에 채팅방 삭제
- [x] 채팅방 생성 때 만들었던 토픽 삭제
- [x] 채팅방에 저장된 메시지들 삭제

<br>

## 🤝 관련 이슈
- #95 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
