### ISSUE TITLE
[FEAT]: 로그인, 로그아웃 DB에 히스토리 저장

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#152]
## 📌 이슈 내용
> 비정상적인 로그아웃을 방지하기 위한 로그인, 로그아웃 히스토리 구현

<br>

## 📝 To-do
- [ ] 로그인 시 히스토리 저장 로직 successHandler에 추가
- [ ] 로그아웃 시 히스토리 저장 로직 memberService logout에 추가
- [ ] 회원탈퇴 시 히스토리에 삭제 날짜 업데이트
- [ ] 쿠키에 expire 설정

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [ ] issue 제목은 유의미한가?
- [ ] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
