### ISSUE TITLE
[FIX]: 알림 구독시 lastEventId값을 헤더로 받게 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#153]
## 🤷‍♀ 문제 상황
> 알림 구독시 lastEventId값을 파라미터로 받고 있었는데 다시 헤더로 받는걸로 변경

<br>

## ✨ 해결 방법
> lastEventId값 헤더로 받도록 수정

<br>

## 📝 To-do
- [x] lastEventId값 헤더로 받도록 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
