### ISSUE TITLE
[FEAT]: 채팅방 삭제 시 읽지 않은 메시지, 채팅방 입장 및 퇴장 레디스 값 삭제 기능 구현

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#158]
## 📌 이슈 내용
> 채팅방 삭제와 읽지 않은 메시지 & 채팅방 입장 및 퇴장 브랜치가 달라 삭제 기능을 구현하지 못해 추가 구현

<br>

## 📝 To-do
- [x] 채팅방 삭제 시 레디스에 저장된 읽지 않은 메시지 삭제
- [x] 채팅방 삭제 시 레디스에 저장된 채팅방 입장 및 퇴장 기록 삭제

<br>

## 🤝 관련 이슈
- #137 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
