### ISSUE TITLE
[FIX]: 채팅 기능 사용시 두번 씩 메시지가 전달되는 버그 발생

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#160]
## 🤷‍♀ 문제 상황
> 메시지를 보내면 보내는 사람은 보낸 메시지와 받는 메시지를 받고 받는 사람은 받는 메시지를 두 번 받는 상황 발생

<br>

## ✨ 해결 방법
> 어떻게 해결했는지 적어주세요.

<br>

## 📝 To-do
- [ ] 보낸 사람은 자신이 보낸 메시지만 출력
- [ ] 받는 사람은 받는 메시지 하나만 출력

<br>

## 🤝 관련 이슈
- #137 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
