### ISSUE TITLE
[FIX]: 피드백 받은 내용 적용하기

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#19]
## 🤷‍♀ 문제 상황
> 불필요한 코드들 수정

<br>

## ✨ 해결 방법
> 관련 내용 논의 후 각자 담당 부분 수정하기

<br>

## 📝 To-do
- [x] 서비스에서 엔티티를 반환하도록 수정
- [x] 와일드카드 삭제
- [x] 글로벌 예외 처리 코드 수정
- [x] 커스텀 예외처리 대신 자바에서 제공되는 예외를 사용하도록 수정
- [x] 커스텀 예외가 필요하면 기본 제공되는 예외를 상속해서 사용하도록 수정
- [x] 테스트 코드 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
