### ISSUE TITLE
[FEAT]: 주문관련 api 테스트 코드 추가

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#27]
## 📌 이슈 내용
> 주문 생성 api 테스트 코드 추가

<br>

## 📝 To-do
- [x] 주문 생성 api 테스트 코드 작성

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
