### ISSUE TITLE
[FIX]: 즉시 구매 시 동시성 이슈

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#29]
## 🤷‍♀ 문제 상황
> 여러 명의 회원이 즉시 구매를 진행하려고 하는 경우 동시성 이슈 발생

<br>

## ✨ 해결 방법
> Redis 분산락을 이용하여 해결
<details>
  <summary>커스텀 어노테이션 및 aop</summary>
  
  ```java
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface RedissonLock {

    String value(); // Lock의 이름 (고유값)

    long waitTime() default 5000L; // Lock 획득을 시도하는 최대 시간 (ms)

    long leaseTime() default 3000L; // 락을 획득한 후, 점유하는 최대 시간 (ms)
}
```
```java
@Slf4j
@Aspect
@Component
@RequiredArgsConstructor
public class RedissonLockAspect {

    private final RedissonClient redissonClient;
    private final AopForTransaction aopForTransaction;

    private final SpelExpressionParser parser = new SpelExpressionParser();

    @Around("@annotation(com.ddang.usedauction.aop.RedissonLock)")
    public void redissonLock(ProceedingJoinPoint joinPoint) throws Throwable {

        MethodSignature signature = (MethodSignature) joinPoint.getSignature(); // 현재 실행 중인 메서드의 시그니처
        Method method = signature.getMethod(); // 메소드 객체를 가져옴
        RedissonLock annotation = method.getAnnotation(
            RedissonLock.class); // RedissonLock 어노테이션을 가져옴
        String lockKey = parseSpel(annotation.value(), joinPoint);
        log.info("lockKey = {}", lockKey);

        RLock lock = redissonClient.getLock(lockKey);

        try {
            boolean lockable = lock.tryLock(annotation.waitTime(), annotation.leaseTime(),
                TimeUnit.MILLISECONDS); // 최대 waitTime 동안 락을 얻기 위해 시도, leaseTime 동안 락 사용
            if (!lockable) {
                log.error("Lock 획득 실패 = {}", lockKey);
                return;
            }

            log.info("Lock 얻고 로직 실행");
            aopForTransaction.proceed(joinPoint); // 어노테이션이 선언된 메소드를 별도의 트랜잭션으로 실행
        } catch (InterruptedException e) {
            log.error("Lock 에러 발생", e);
            throw e;
        } finally {
            lock.unlock();
        }
    }

    // 전달받은 Lock의 이름을 Spring Expression Language 로 파싱
    private String parseSpel(String spel, ProceedingJoinPoint joinPoint) {
        StandardEvaluationContext context = new StandardEvaluationContext();
        Object[] args = joinPoint.getArgs();
        String[] paramNames = ((org.aspectj.lang.reflect.MethodSignature) joinPoint.getSignature()).getParameterNames();

        for (int i = 0; i < args.length; i++) {
            context.setVariable(paramNames[i], args[i]);
        }

        return parser.parseExpression(spel).getValue(context, String.class);
    }
}
```
- Spring Expression Language
```java
@RedissonLock("#auctionId")
public void instantPurchaseAuction(Long, auctionId, String memberId) {
    ...
}
```

</details>

> 트랜잭션 분리를 통해 데이터 정합성 보장

<details>
  <summary>트랜잭션 분리</summary>
  
```java
// 트랜잭션 분리를 위한 클래스
@Component
public class AopForTransaction {

    @Transactional
    public Object proceed(final ProceedingJoinPoint joinPoint) throws Throwable {

        return joinPoint.proceed();
    }
}
```
- 트랜잭션 분리 이전
  - 요청 1에서 락을 획득
  - 요청 1의 트랜잭션 시작
  - 즉시 구매를 진행하고 경매를 종료
  - 락이 해제되고, 다른 요청 2에서 락을 획득
  - 요청 2의 트랜잭션 시작
  - 커밋이 된 상태가 아니기에 요청 2에서는 아직 경매가 진행중
  - 요청 1의 커밋 진행

- 트랜잭션 분리 이후
  - 요청 1에서 락을 획득
  - 요청 1의 트랜잭션 시작
  - 즉시 구매 진행 및 경매 종료
  - 요청 1의 트랜잭션 커밋
  - 락 해제
  - 요청 2에서 락 획득
  - 요청 2의 트랜잭션 시작
  - 요청 1의 트랜잭션이 커밋된 상태이므로 경매는 이미 종료됨
  - 요청 2 실패

</details>

<details>
  <summary>테스트</summary>
  
```java
@Test
@DisplayName("즉시 구매 동시성 테스트")
void instantPurchaseAuctionWithoutLock() throws InterruptedException {

    long memberCount = 30;
    ExecutorService executorService = Executors.newFixedThreadPool((int) memberCount);
    CountDownLatch latch = new CountDownLatch((int) memberCount);

    AtomicInteger successCount = new AtomicInteger();
    AtomicInteger failCount = new AtomicInteger();
    for (long i = 1; i <= memberCount; i++) {
        long finalI = i;
        executorService.submit(() -> {
            try {
                auctionService.instantPurchaseAuction(auctionId, "test" + finalI);
                successCount.incrementAndGet();
            } catch (Exception e) {
                failCount.incrementAndGet();
            } finally {
                latch.countDown();
            }
        });
    }

    latch.await();

    assertEquals(1, successCount.get()); // 1개 성공
    assertEquals(memberCount - 1, failCount.get()); // 나머지 29개 실패
}
```

</details>

<br>

## 📝 To-do
- [x] 먼저 락을 획득한 트랜잭션이 즉시 구매에 성공하며 이후 트랜잭션은 실패해야 함

<br>

## 🤝 관련 이슈
- #14 

<br>

### Reference
[참고](https://helloworld.kurly.com/blog/distributed-redisson-lock/#3-%EB%B6%84%EC%82%B0%EB%9D%BD%EC%9D%84-%EB%B3%B4%EB%8B%A4-%EC%86%90%EC%89%BD%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98%EB%8A%94-%EC%97%86%EC%9D%84%EA%B9%8C)

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
