### ISSUE TITLE
[FEAT]: JWT 사용하지 않은 채팅 기능

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#3]
## 📌 이슈 내용
> WebSocket,STOMP,Redis를 이용한 채팅 기능 구현

<br>

## 📝 To-do
- [x] 간단한 회원가입 구현
- [x] chatConfig 클래스 구현 (stomp 접속 주소 url, 메시지 송수신 엔드포인트 설정, CORS 정책)
- [x] webConfig 클래스 구현 (CORS 문제 해결하기 위한 config 파일)
- [x] RedisConfig 클래스 구현
- [x] RedisRepoConfig 클래스 구현 
- [x] chatRoom, chatMessage 엔티티 클래스 구현
- [x] controller, service, repository 구현

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference
[STOMP 개념](https://wonsjung.tistory.com/403)
<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
