### ISSUE TITLE
[FIX]: develop 실행안되는 이슈 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#32]
## 🤷‍♀ 문제 상황
> develop 브랜치에서 어플리케이션이 실행이 안되는 이슈

<br>

## ✨ 해결 방법
> GlobalExceptionHandler에서 필요없는 import문 삭제

<br>

## 📝 To-do
- [x] GlobalExceptionHandler에서 필요없는 import문 삭제

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
