### ISSUE TITLE
[FEAT]: 판매 내역 및 구매 내역 조회

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#35]
## 📌 이슈 내용
> 판매 내역 및 구매 내역 조회 기능을 구현합니다.

<br>

## 📝 To-do
- [x] 판매 및 구매 내역을 조회합니다.
- [x] 내역 중 경매 진행 중인 것과 경매 마감된 내역을 구분하여 조회합니다.
- [x] 검색이 가능합니다
- [x] 가격순, 날짜별 , 최신순, 오래된 순으로 필터링이 가능합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
