### ISSUE TITLE
[FIX]: 포인트, 결제 관련 테스트 코드 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#36]
## 🤷‍♀ 문제 상황
> GlobalExceptionHandler의 변경으로 특정 테스트 코드에서 테스트가 실패함

<br>

## ✨ 해결 방법
> 예외처리 부분 코드를 수정

<br>

## 📝 To-do
- [x] 포인트 관련 테스트 코드 수정
- [x] 결제 관련 테스트 코드 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
