### ISSUE TITLE
[FEAT]: 입찰 및 경매 가격 실시간 업데이트

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#43]
## 📌 이슈 내용
> 회원은 경매에 참여하여 입찰을 진행합니다.
> 입찰이 진행될 때마다 최고입찰가가 변경됩니다.

<br>

## 📝 To-do
- [x] 여러 회원이 동시에 입찰을 진행하는 경우 동시성 이슈 해결
- [x] 입찰이 진행된 후 최고입찰가의 변동을 db에 저장합니다.
- [x] 회원이 입찰을 시도할 때 현재 회원이 다른 경매에서 최고 입찰가로 입찰을 한 경우 현재 보유 포인트에서 최고입찰가 만큼 차감하여 입찰을 진행할 수 있는지 여부를 판단합니다.
- [x] 이미 종료된 경매의 경우 입찰이 불가합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
