### ISSUE TITLE
[FIX]: 판매 및 구매 내역 조회 시 수령 방법 조회

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#45]
## 🤷‍♀ 문제 상황
> 판매 및 구매 내역 조회 시 수령 방법에 대한 필드가 없어 조회가 되지 않는 문제

<br>

## ✨ 해결 방법
> 수령 방법에 대한 필드를 추가하여 조회 가능하도록 함

<br>

## 📝 To-do
- [x] 판매 및 구매 내역 조회 시 수령 방법에 대한 필드가 존재해야 함

<br>

## 🤝 관련 이슈
- #35

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
