### ISSUE TITLE
[FEAT]: 알림 응답에 경매 pk값 추가

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#47]
## 📌 이슈 내용
> 알림클릭시 관련 경매의 상세페이지로 이동할 수 있도록 알림 응답에 경매 pk값을 추가합니다.

<br>

## 📝 To-do
- [x] 알림 응답에 경매 pk값을 추가합니다.

<br>

## 🤝 관련 이슈
- #38 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
