### ISSUE TITLE
[FIX]: 구매자가 구매확정시 판매자에게 구매확정 알림이 전송되지 않는 이슈

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#49]
## 🤷‍♀ 문제 상황
> 구매자가 구매확정시 판매자에게 구매확정 알림이 전송되지 않는 이슈
> 자동 구매 확정시에만 알림이 전송되고 있음

<br>

## ✨ 해결 방법
> handleAuctionAutoConfirmEvent()에 있는 알림전송코드를 confirmAuction()으로 이동

<br>

## 📝 To-do
- [x] handleAuctionAutoConfirmEvent()에 있는 알림전송코드를 confirmAuction()으로 이동

<br>

## 🤝 관련 이슈

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
