### ISSUE TITLE
[FIX]: 알림조회시 최근 1달까지 알림만 조회되도록 수정

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#52]
## 🤷‍♀ 문제 상황
> 알림 조회시 모든 기간의 알림이 조회되었습니다.

<br>

## ✨ 해결 방법
> Query 어노테이션을 사용해 최근 1달까지의 알림만 조회할 수 있도록 수정했습니다.

<br>

## 📝 To-do
- [x] 알림 조회시 최근 1달까지의 알림만 조회되도록 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
