### ISSUE TITLE
[REFACTOR]: 경매 서비스 코드 리펙토링

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#53]
## 🤷‍♀ 문제 상황
> 코드가 너무 길어져 가독성이 떨어짐

<br>

## ✨ 해결 방법
> private 메소드로 분리하여 가독성 향상

<br>

## 📝 To-do
- [x] 너무 길어지는 코드는 private 메소드로 따로 분리한다.
- [x] 메소드명을 알맞게 작성하여 어떤 기능인지 이해되도록 리펙토링한다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
