### ISSUE TITLE
[FEAT]: 즉시구매 알림 타입 추가

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#55]
## 📌 이슈 내용
> 현재 즉시구매시 전송되는 알림 내용이 경매종료시와 동일한 알림내용을 전달하고 있습니다.
> 둘을 구분하기 위해 새로운 알림타입을 추가하고 알림 내용도 변경하기로 했습니다.

<br>

## 📝 To-do
- [x] 즉시구매 알림 타입을 추가합니다.
- [x] 즉시구매시 전송하는 알림내용을 변경합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
