### ISSUE TITLE
[FIX]: 알림전송시 응답내용에 경매제목 추가

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#59]
## 🤷‍♀ 문제 상황
> 알림전송시 응답내용에 경매제목을 추가합니다.

<br>

## ✨ 해결 방법
> 알림 응답 내용을 수정합니다.

<br>

## 📝 To-do
- [x] 알림전송시 응답내용에 경매제목을 추가합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
