### ISSUE TITLE
[FEAT]: 카테고리 조회

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#60]
## 📌 이슈 내용
> 필터링을 통해 해당 카테고리에 속한 상품들만 조회하기 위한 기능 구현
> 상품 등록 시 카테고리 조회를 통해 대분류와 소분류를 선택할 수 있는 기능 구현

<br>

## 📝 To-do
- [x] 등록된 대분류 카테고리를 조회합니다.
- [x] 특정 대분류에 속한 모든 소분류 카테고리를 조회합니다.
- [ ] 대분류 카테고리에 이미지가 저장되어야 합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
