### ISSUE TITLE
[FIX]: 구매자가 즉시 구매 후 구매 확정 했음에도 다시 한 번 자동구매확정 로직이 실행되는 문제

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#62]
## 🤷‍♀ 문제 상황
> 구매자가 즉시 구매를 진행
> 구매자가 구매 확정을 진행
> 자동구매확정(경매 종료 일주일 후 자동구매확정) 로직이 실행
> 결국 구매 확정이 2번 실행되는 상황 발생

<br>

## ✨ 해결 방법
> 자동 구매 확정 진행 시 현재 거래 상태를 확인하여 이미 거래가 종료(구매확정을 진행함)되었다면 구매확정이 진행되지 않도록 코드 수정

<br>

## 📝 To-do
- [x] 즉시 구매 이후 구매자가 구매 확정을 한 경우 자동구매확정이 진행되지 않아야 합니다.

<br>

## 🤝 관련 이슈
- #34 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
