### ISSUE TITLE
[FIX]: 보안 컨텍스트에 인증 정보 설정 시 값이 null 발생하는 에러

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#64]
## 🤷‍♀ 문제 상황
> 로그인한 사용자 인증 정보가 출력되는지 테스트하기 위해 accessToken 값을 쿠키에 담고 
> 컨트롤러에 @AuthenticationPrincipal 을 사용했는데 로그인 객체가 null인 상황이 발생해
> JwtAuthenticationFilter의 setAuthentication 부분에서 Authentication의 값은 잘 들어가서
> SecurityContext에 값이 안들어가는걸 확인하였다.
<br>

## ✨ 해결 방법
> TokenProvider의 getAuthentication 메서드에서 UserDetails 객체를 생성하고 이를
> UsernamePasswordAuthenticationToken에 설정하여 반환하였다.
> 컨트롤러에서는 UserDetails, OAuth2User를 상속받은 PrincipalDetails를 파라미터로 받는다.
> getAuthentication 메서드에서 Principal 객체를 생성해 UsernamePasswordAuthenticationToken 설정하여 반환하였다.

<br>

## 📝 To-do
- [x] 토큰에 저장된 로그인한 유저의 정보가 출력되어야 함

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
