### ISSUE TITLE
[FEAT]: CI/CD 도입

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#66]
## 📌 이슈 내용
> Github Actions를 사용해 CI/CD 워크플로우 설정 및 자동화

<br>

## 📝 To-do
- [x] ci용 스크립트 추가
- [x] cd용 스크립트 추가
- [x] docker-compose 파일 생성
- [x] .env 파일 생성
- [x] 깃허브 시크릿값 추가

<br>

## 🤝 관련 이슈
- #89 
- #96 
- #98 
- #100 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
