### ISSUE TITLE
[FIX]: 비회원이 권한이 필요하지 않은 기능을 사용할 때 권한을 검증하는 에러

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#67]
## 🤷‍♀ 문제 상황
> 비회원이 유저의 권한을 검증하지 않는 기능을 사용할 때 권한을 검증하는 에러 발생
<br>

## ✨ 해결 방법
> JwtAuthenticationFilter의 accessToken 검증하는 조건문에 조건을 추가하였음

<br>

## 📝 To-do
- [x] 권한이 필요하지 않은 기능을 사용할 때 토큰 검증을 하지 않아야 한다.

<br>

## 🤝 관련 이슈
- #22

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
