### ISSUE TITLE
[FIX]: 비회원이 권한이 필요한 API를 사용할 때 에러메시지 출력하지 않는 문제

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#70]
## 🤷‍♀ 문제 상황
>USER 권한이 필요한 API를 비회원이 사용했을 때 에러메시지가 아닌 html 파일이 반환됨

<br>

## ✨ 해결 방법
> 인증되지 않은 사용자가 접근할 때 401 Unauthorized 상태 코드, 메시지를 반환하도록 JwtAuthenticationEntryPoint,
권한이 부족한 사용자가 접근할 때 403 Forbidden 상태 코드, 메시지를 반환하도록 JwtAccessDeniedHandler 설정하였다.
SecurityConfig에서 exceptionHandling()을 통해 예외 처리하였다.

<br>

## 📝 To-do
- [x] 인증되지 않은 사용자가 접근하려고 할 때, 401 상태 코드와 메시지 반환
- [x] 권한이 부족한 사용자가 접근하려고 할 때, 403 상태 코드와 메시지 반환

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?

**Comment by JinhwanB** [comment]
제가 잘 못 확인한거 같아요
토큰은 쿠키에 잘 저장이 됩니다
권한 인증에 대한 에러 401, 403 코드만 잘 응답되면 될 거 같아요!
