### ISSUE TITLE
[FEAT]: 최근 본 경매 리스트 저장 및 조회

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#71]
## 📌 이슈 내용
> 최근 조회한 경매 5개를 조회 가능합니다.

<br>

## 📝 To-do
- [x] 5개의 최근 조회한 경매를 조회할 수 있습니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
