### ISSUE TITLE
[FIX]: 회원 enum 이름 변경

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#74]
## 🤷‍♀ 문제 상황
> PrincipalOauth2UserService  signUp 메서드에 Role 이름 변경된게 반영이 되지 않음

<br>

## ✨ 해결 방법
> Role enum 이름 변경
<br>

## 📝 To-do
- [x] enum 이름 변경

<br>

## 🤝 관련 이슈
- #22 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
