### ISSUE TITLE
[FEAT]: auction, transaction 인증 인가 테스트

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#88]
## 📌 이슈 내용
> auction, transaction 컨트롤러에서 인증 인가 테스트 진행합니다.

<br>

## 📝 To-do
- [x] 회원인 경우 인증 인가 테스트에 성공합니다.
- [x] 회원이 아닌 경우 401 코드를 반환합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
