### ISSUE TITLE
[FIX]: ec2에서 docker pull 및 실행

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#89]
## 🤷‍♀ 문제 상황
> CD과정중 ec2에서 docker를 pull하지 않고 있습니다. 
> pull 및 실행할 수 있도록 스크립트를 수정합니다.

<br>

## ✨ 해결 방법
> 스크립트를 수정합니다.

<br>

## 📝 To-do
- [x] CD 스크립트 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
