### ISSUE TITLE
[FEAT]: 구매 확정 api 구현

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#9]
## 📌 이슈 내용
> 경매 종료 후 구매자는 구매 확정을 통해 최종 거래 종료
> 구매 확정 시 판매자에게 구매 금액 만큼 포인트 추가

<br>

## 📝 To-do
- [x] 구매 확정 시 request 유효성 검증을 실시합니다.
- [x] 구매 확정은 일주일 동안 유효하며 그 이후는 자동 구매확정 처리가 됩니다.
- [x] 구매 확정 시 해당하는 경매가 진행 중인 경매인 경우 예외가 발생합니다.
- [x] 구매 확정 시 구매자의 포인트가 구매 가격보다 적은 경우 예외가 발생합니다.
- [x] 구매 확정 시 판매자의 포인트 변경할 때 동시성 이슈 해결을 위한 분산락 구현
- [x] 구매 확정 시 구매자가 구매한 가격만큼 판매자의 포인트가 증가합니다.

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
