### ISSUE TITLE
[FEAT]: 핫 5 경매 조회 구현

### ISSUE THREAD

**Issue by JinhwanB** [UsedAuction/back-end#92]
## 📌 이슈 내용
> 경매 중 참여자가 많은순으로 5개의 경매를 조회합니다.

<br>

## 📝 To-do
- [x] 참여자가 많은 5개의 경매를 조회합니다.

<br>

## 🤝 관련 이슈

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
