### ISSUE TITLE
[FEAT]: 경매 종료 후 채팅방 생성 기능 추가

### ISSUE THREAD

**Issue by sh035** [UsedAuction/back-end#95]
## 📌 이슈 내용
> 경매 종료 처리(즉시 구매 포함) 후  판매자와 구매자가 속한 채팅방이 생성 기능을 추가하였습니다.

<br>

## 📝 To-do
- [x] 경매 종료 후 판매자 혹은 구매자인 회원만 채팅방이 만들어진다.
- [x] 채팅방에 속한 판매자, 구매자만 채팅을 칠 수 있다.

<br>

## 🤝 관련 이슈
- #3 

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
