### ISSUE TITLE
[FIX]: 도커이미지가 설정되지 않는 이슈2

### ISSUE THREAD

**Issue by Cathunder** [UsedAuction/back-end#98]
## 🤷‍♀ 문제 상황
> docker-compose에서 BACKEND_APP_IMAGE_NAME 환경변수가 설정되지 않음

<br>

## ✨ 해결 방법
> docker-compose 실행시 해당 환경변수를 전달할 수 있도록 수정

<br>

## 📝 To-do
- [x] docker-compose 실행시 해당 환경변수를 전달할 수 있도록 수정

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
